#!/bin/bash
# ═══════════════════════════════════════════════════════════
#  Script MGVPN - PANEL PRINCIPAL
#  Diseño profesional con sistema HWID
# ═══════════════════════════════════════════════════════════

# Definir colores
verde="\e[1;32m"
v="\e[0;32m"
cyan="\e[1;36m"
rojo="\e[1;31m"
r="\e[0;31m"
blanco="\e[1;37m"
b="\e[0;37m"
amarillo="\e[1;33m"
a="\e[0;33m"
fin="\e[0m"

fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
[[ ! -e /usr/lib/sshplus ]] && rm -rf /bin/menu > /dev/null 2>&1
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "${amarillo}["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "${rojo}#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "${amarillo}]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "${amarillo}["
done
echo -e "${amarillo}]\e[1;37m -${verde} OK !\e[1;37m"
tput cnorm
}

IP=$(cat /etc/IP 2>/dev/null || echo "DESCONOCIDO")
x="ok"

menu ()
{
velocity () {
aguarde () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
[[ ! -d /etc/SSHPlus ]] && rm -rf /bin/menu
${comando[0]} > /dev/null 2>&1
${comando[1]} > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  ${amarillo}AGUARDE \e[1;37m- ${amarillo}["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "${rojo}#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "${amarillo}]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  ${amarillo}AGUARDE \e[1;37m- ${amarillo}["
done
echo -e "${amarillo}]\e[1;37m -${verde} OK !\e[1;37m"
tput cnorm
}
fun_tst () {
speedtest --share > speed
}
echo ""
echo -e "   ${verde}TESTANDO LA VELOCIDAD Del VPS !\e[0m"
echo ""
aguarde 'fun_tst'
echo ""
png=$(cat speed | sed -n '7 p' |awk -F : {'print $NF'})
down=$(cat speed | sed -n '8 p' |awk -F :  {'print $NF'})
upl=$(cat speed | sed -n '9 p' |awk -F :  {'print $NF'})
lnk=$(cat speed | sed -n '10 p' |awk {'print $NF'})
echo -e "═══════════════════════════════════════════════════════"
echo -e "${verde}PING (LATENCIA):\e[1;37m$png"
echo -e "${verde}DOWNLOAD:\e[1;37m$down"
echo -e "${verde}UPLOAD:\e[1;37m$upl"
echo -e "${verde}LINK: ${cyan}$lnk\e[0m"
echo -e "═══════════════════════════════════════════════════════"
rm -rf $HOME/speed
}
#limiter
function limit1 () {
   clear
   echo -e "\n${verde}INICIANDO el LIMITER... \e[0m"
   echo ""
   fun_bar 'screen -dmS limiter limiter' 'sleep 3'
   [[ $(grep -wc "limiter" /etc/autostart) = '0' ]] && {
       echo -e "ps x | grep 'limiter' | grep -v 'grep' && echo 'ON' || screen -dmS limiter limiter" >> /etc/autostart
   } || {
       sed -i '/limiter/d' /etc/autostart
	   echo -e "ps x | grep 'limiter' | grep -v 'grep' && echo 'ON' || screen -dmS limiter limiter" >> /etc/autostart
   }
   echo -e "\n${verde}  LIMITER ACTIVO !\e[0m"
   sleep 3
   menu
}
function limit2 () {
   clear
   echo -e "${verde}PARANDO el LIMITER... \e[0m"
   echo ""
   fun_stplimiter () {
      sleep 1
      screen -r -S "limiter" -X quit
      screen -wipe 1>/dev/null 2>/dev/null
      [[ $(grep -wc "limiter" /etc/autostart) != '0' ]] && {
          sed -i '/limiter/d' /etc/autostart
      }
      sleep 1
   }
   fun_bar 'fun_stplimiter' 'sleep 3'
   echo -e "\n${rojo} LIMITER PARADO !\e[0m"
   sleep 3
   menu
}
function limit_ssh () {
[[ $(ps x | grep "limiter"|grep -v grep |wc -l) = '0' ]] && limit1 || limit2
}
#onlineapp
function onapp1 () {
   clear
   echo -e "\n${verde}INICIANDO  ONLINE APP... \e[0m"
   echo ""
   apt install apache2 -y > /dev/null 2>&1
   sed -i "s/Listen 80/Listen 8888/g" /etc/apache2/ports.conf >/dev/null 2>&1
   service apache2 restart
   rm -rf /var/www/html/server >/dev/null 2>&1
   mkdir /var/www/html/server >/dev/null 2>&1
   fun_bar 'screen -dmS onlineapp onlineapp' 'sleep 3'
   [[ $(grep -wc "onlineapp" /etc/autostart) = '0' ]] && {
       echo -e "ps x | grep 'onlineapp' | grep -v 'grep' && echo 'ON' || screen -dmS onlineapp onlineapp" >> /etc/autostart
   } || {
       sed -i '/onlineapp/d' /etc/autostart
	   echo -e "ps x | grep 'onlineapp' | grep -v 'grep' && echo 'ON' || screen -dmS onlineapp onlineapp" >> /etc/autostart
   }
   IP=$(wget -qO- ipv4.icanhazip.com) >/dev/null 2>&1
   echo -e "\n${verde}  ONLINE APP ATIVO !\e[0m"
   echo -e "${rojo} ${amarillo}URL de Usuários Online para usar no App\e[0m"
   echo -e " http://$IP:8888/server/online"
   sleep 10
   menu
}
function onapp2 () {
   clear
   echo -e "${verde}PARANDO  ONLINE APP... \e[0m"
   echo ""
   fun_stponlineapp () {
      sleep 1
      screen -r -S "onlineapp" -X quit
      screen -wipe 1>/dev/null 2>/dev/null
      [[ $(grep -wc "onlineapp" /etc/autostart) != '0' ]] && {
          sed -i '/onlineapp/d' /etc/autostart
      }
      sleep 1
   }
   fun_bar 'fun_stponlineapp' 'sleep 3'
   rm -rf /var/www/html/server >/dev/null 2>&1
   echo -e "\n${rojo} ONLINE APP PARADO !\e[0m"
   sleep 3
   menu
}
function onapp_ssh () {
[[ $(ps x | grep "onlineapp"|grep -v grep |wc -l) = '0' ]] && onapp1 || onapp2
}
##
function autoexec () {
   if grep "menu;" /etc/profile > /dev/null; then
      clear
      echo -e "${verde}DESACTIVANDO AUTO EJECUCION\e[0m"
      offautmenu () {
         sed -i '/menu;/d' /etc/profile
      }
      echo ""
      fun_bar 'offautmenu'
      echo ""
      echo -e "${rojo}AUTO EJECUCION DESACTIVADO!\e[0m"
      sleep 1.5s
      menu2
   else
      clear
      echo -e "${verde}ACTIVANDO AUTO EJECUCION\e[0m"
      autmenu () {
         grep -v "^menu;" /etc/profile > /tmp/tmpass && mv /tmp/tmpass /etc/profile
         echo "menu;" >> /etc/profile
      }
      echo ""
      fun_bar 'autmenu'
      echo ""
      echo -e "${verde}AUTO EXECUCION ACTIVADO!\e[0m"
      sleep 1.5s
      menu2
   fi
}
#menu2
menu2 (){
[[ -e /etc/Plus-torrent ]] && stsf=$(echo -e "${verde}◉ ") || stsf=$(echo -e "${rojo}○ ")
stsbot=$(ps x | grep "bot_plus"|grep -v grep > /dev/null && echo -e "${verde}◉ " || echo -e "${rojo}○ ")
stsbotteste=$(ps x | grep "bot_teste"|grep -v grep > /dev/null && echo -e "${verde}◉ " || echo -e "${rojo}○ ")
autm=$(grep "menu;" /etc/profile > /dev/null && echo -e "${verde}◉ " || echo -e "${rojo}○ ")
[[ ! -e /usr/lib/licence ]] && rm -rf /bin > /dev/null 2>&1
if [[ "$(grep -c "Ubuntu" /etc/issue.net)" = "1" ]]; then
system=$(cut -d' ' -f1 /etc/issue.net)
system+=$(echo ' ')
system+=$(cut -d' ' -f2 /etc/issue.net |awk -F "." '{print $1}')
elif [[ "$(grep -c "Debian" /etc/issue.net)" = "1" ]]; then
system=$(cut -d' ' -f1 /etc/issue.net)
system+=$(echo ' ')
system+=$(cut -d' ' -f3 /etc/issue.net)
else
system=$(cut -d' ' -f1 /etc/issue.net)
fi
_ons=$(ps -x | grep sshd | grep -v root | grep priv | wc -l)
[[ "$(cat /etc/SSHPlus/Exp)" != "" ]] && _expuser=$(cat /etc/SSHPlus/Exp) || _expuser="0"
[[ -e /etc/openvpn/openvpn-status.log ]] && _onop=$(grep -c "10.8.0" /etc/openvpn/openvpn-status.log) || _onop="0"
[[ -e /etc/default/dropbear ]] && _drp=$(ps aux | grep dropbear | grep -v grep | wc -l) _ondrp=$(($_drp - 1)) || _ondrp="0"
_onli=$(($_ons + $_onop + $_ondrp))
_ram=$(printf ' %-9s' "$(free -h | grep -i mem | awk {'print $2'})")
_usor=$(printf '%-8s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")
_usop=$(printf '%-1s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
_core=$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")
_system=$(printf '%-14s' "$system")
_hora=$(printf '%(%H:%M:%S)T')
_onlin=$(printf '%-5s' "$_onli")
_userexp=$(printf '%-5s' "$_expuser")
_tuser=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)
clear
echo -e "═══════════════════════════════════════════════════════"
echo -e "${cyan}  SISTEMA         MEMORIA RAM      PROCESADOR"
echo -e "${amarillo}  $_system   Ram:${verde}$_ram     Cpu: ${amarillo}$_core\e[0m"
echo -e "${rojo}  Script MGVPN     💾${verde}$_usor  🖥${verde}$_usop\e[0m"
echo -e "═══════════════════════════════════════════════════════"
[[ ! -e /tmp/att ]]  && {
    echo -e "${amarillo}  Onlines:${verde} $_onlin     ${blanco}Expirados: ${rojo}$_userexp ${amarillo}Total: ${verde}$_tuser\e[0m"
} || {
    echo -e "  ${rojo} ACTUALIZACION DISPONIBLE  ${rojo}!✅${fin}"
}
echo -e "═══════════════════════════════════════════════════════"
echo ""
echo -e "${cyan}[21]${amarillo} ADICIONAR HOST      ${cyan}[28] ${amarillo} EDITAR PASS ROOT"
echo -e "${cyan}[22]${amarillo} REMOVER HOST        ${cyan}[29] ${amarillo} AUTO INICIO $autm"
echo -e "${cyan}[23]${amarillo} REINICIAR SISTEMA   ${cyan}[30] ${amarillo} ACTUALIZAR SCRIPT"
echo -e "${cyan}[24]${amarillo} REINICIAR SERVICIOS ${cyan}[31]${amarillo} BORRAR SCRIPT"
echo -e "${cyan}[25]${amarillo} BLOCK TORRENT $stsf  ${cyan}[32]${amarillo} VOLVER"
echo -e "${cyan}[26]${amarillo} BOT TELEGRAM $stsbot   ${cyan}[00]${amarillo} SALIR"
echo -e "${cyan}[27]${amarillo} BOT TESTE $stsbotteste"
echo ""
echo -e "═══════════════════════════════════════════════════════"
echo ""
echo -ne "${verde}  QUE DESEA HACER ${amarillo}?${rojo}?${blanco} : "; read x
case "$x" in
   21)
   clear
   addhost
   echo -ne "\n${rojo}ENTER ${amarillo}para volver al ${verde}MENU!\e[0m"; read
   menu2
   ;;
   22)
   clear
   delhost
   echo -ne "\n${rojo}ENTER ${amarillo}para volver al ${verde}MENU!\e[0m"; read
   menu2
   ;;
   23)
   clear
   reiniciarsistema
   ;;
   24)
   clear
   reiniciarservicos
   sleep 3
   ;;
   25)
   blockt
   ;;
   26)
   botssh
   ;;
   27)
   botteste.sh
   ;;
   28)
   clear
   senharoot
   sleep 3
   ;;
   29)
   autoexec
   ;;
   30)
   attscript
   ;;
   31)
   clear
   delscript
   ;;
   32)
   menu
   ;;
   0|00)
   echo -e "${rojo}SALIENDO...\e[0m"
   sleep 2
   clear
   exit;
   ;;
   *)
   echo -e "\n${rojo}OPCION INVALIDA !\e[0m"
   sleep 2
esac
}
while true $x != "ok"
do
stsl=$(ps x | grep "limiter"|grep -v grep > /dev/null && echo -e "${verde}◉ " || echo -e "${rojo}○ ")
pyt=$(ps x | grep "python3"|grep -v grep > /dev/null && echo -e "${verde}◉ " || echo -e "${rojo}○ ")
stsu=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "${verde}◉ " || echo -e "${rojo}○ ")
if [[ "$(grep -c "Ubuntu" /etc/issue.net)" = "1" ]]; then
system=$(cut -d' ' -f1 /etc/issue.net)
system+=$(echo ' ')
system+=$(cut -d' ' -f2 /etc/issue.net |awk -F "." '{print $1}')
elif [[ "$(grep -c "Debian" /etc/issue.net)" = "1" ]]; then
system=$(cut -d' ' -f1 /etc/issue.net)
system+=$(echo ' ')
system+=$(cut -d' ' -f3 /etc/issue.net)
else
system=$(cut -d' ' -f1 /etc/issue.net)
fi
_ons=$(ps -x | grep sshd | grep -v root | grep priv | wc -l)
[[ "$(cat /etc/SSHPlus/Exp)" != "" ]] && _expuser=$(cat /etc/SSHPlus/Exp) || _expuser="0"
[[ -e /etc/openvpn/openvpn-status.log ]] && _onop=$(grep -c "10.8.0" /etc/openvpn/openvpn-status.log) || _onop="0"
[[ -e /etc/default/dropbear ]] && _drp=$(ps aux | grep dropbear | grep -v grep | wc -l) _ondrp=$(($_drp - 1)) || _ondrp="0"
_onli=$(($_ons + $_onop + $_ondrp))
_ram=$(printf ' %-2s' "$(free -h | grep -i mem | awk {'print $2'})")
_usor=$(printf '%-2s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")
usop=$(printf '%-1s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
_core=$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")
_system=$(printf '%-14s' "$system")
_hora=$(printf '%(%H:%M:%S)T')
_onlin=$(printf '%-3s' "$_onli")
CPU_IDLE=$(vmstat 1 2 | tail -1 | awk '{print $15}')
CPU_USAGE=$((100 - CPU_IDLE))
_userexp=$(printf '%-5s' "$_expuser")
_tuser=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)
clear
echo -e "═══════════════════════════════════════════════════════"
echo -e "${cyan}  SISTEMA        MEMORIA RAM      PROCESADOR"
echo -e "${a}  $_system   Ram:${a}$_ram  ${rojo} Cpu:${v} $_core \e[0m"
echo -e "${rojo}  Script MGVPN     💾${v}$_usor     🖥${v} $CPU_USAGE% \e[0m"
echo -e "${a}  Onlines:${v} $_onlin    ${v}Expirados:${r} $_userexp ${b}Total:${v}$_tuser \e[0m"
echo -e "═══════════════════════════════════════════════════════"
echo ""
echo -e "${cyan}  [01]${amarillo} CREAR USUARIO        ${cyan}[11]${amarillo} SPEEDTEST"
echo -e "${cyan}  [02]${amarillo} SISTEMA HWID         ${cyan}[12]${amarillo} BANNER"
echo -e "${cyan}  [03]${amarillo} REMOVER USUARIO      ${cyan}[13]${amarillo} MENU TOKEN"
echo -e "${cyan}  [04]${amarillo} MONITOR ONLINE       ${cyan}[14]${amarillo} PUERTOS ACTIVOS"
echo -e "${cyan}  [05]${amarillo} EDITAR FECHA         ${cyan}[15]${amarillo} BACKUP USER"
echo -e "${cyan}  [06]${amarillo} EDITAR LIMITE        ${cyan}[16]${amarillo} MENU PYTHON3 $pyt"
echo -e "${cyan}  [07]${amarillo} EDITAR CONTRASEÑA    ${cyan}[17]${amarillo} LIMITER $stsl"
echo -e "${cyan}  [08]${amarillo} BORRAR EXPIRADOS     ${cyan}[18]${amarillo} BAD VPN $stsu"
echo -e "${cyan}  [09]${amarillo} INFO DE USUARIOS     ${cyan}[19]${amarillo} LIMPIAR RAM"
echo -e "${cyan}  [10]${amarillo} MENU INSTALADOR      ${cyan}[20]${amarillo} INFO VPS"
echo -e "${rojo}  [00]${amarillo} SALIR               ${cyan}[21]${amarillo} MENU 2"
echo ""
echo -e "═══════════════════════════════════════════════════════"
echo ""
echo -ne "${verde}  QUE DESEA HACER ${amarillo}?${rojo}?${blanco} : "; read x

case "$x" in 
   1 | 01)
   clear
   criarusuario
   echo -ne "\n${rojo} ENTER ${amarillo}para VOLVER al ${verde}MENU!\e[0m"; read
   ;;
   2 | 02)
   clear
   criarhwid
   echo -ne "\n${rojo} ENTER ${amarillo}para VOLVER al ${verde}MENU!\e[0m"; read
   ;;
   3 | 03)
   clear
   remover
   sleep 3
   ;;
   4 | 04)
   clear
   sshmonitor
   echo -ne "\n${rojo}Script MGVPN ${amarillo} VPS: ${verde}wep!\e[0m\n${rojo}ENTER ${amarillo}para VOLVER al ${verde}MENU!\e[0m"; read
   ;;      
   5 | 05)
   clear
   mudardata
   echo -ne "\n${rojo}ENTER ${amarillo}para VOLVER al ${verde}MENU!\e[0m"; read
   ;;
   6 | 06)
   clear
   alterarlimite
   sleep 3
   ;; 
   7 | 07)
   clear
   alterarsenha
   sleep 3
   ;;
   8 | 08)
   clear
   expcleaner
   echo ""
   sleep 3
   ;;     
   9 | 09)
   clear
   infousers
   echo -ne "\n${rojo}Script MGVPN ${amarillo} VPS: ${verde}\e[0m\n${rojo}ENTER ${amarillo}para VOLVER al ${verde}MENU!\e[0m"; read
   ;;
   10)
   conexao
   exit;
   ;;
   11)
   clear
   apt install speedtest-cli -y && speedtest
   echo -ne "\n${rojo}ENTER ${amarillo}para VOLVER al ${verde}MENU!\e[0m"; read
   ;;
   12)
   clear
   banner
   sleep 3
   ;;
   13)
   clear
   wget https://raw.githubusercontent.com/vpsvip7/2d/main/token.sh; chmod 755 *; mv token.sh /bin/token; token
   ;;
   14)
   clear
   netstat -ntpl
   echo -ne "\n${rojo}ENTER ${amarillo}PARA VOLVER AL ${verde}MENU!\e[0m"; read
   ;;
   15)
   userbackup
   echo -ne "\n${rojo}ENTER ${amarillo}PARA VOLVER al ${verde}MENU!\e[0m"; read
   ;;
   16)
   source <(curl -sL https://gitlab.com/diegovip7/SSHPLUS/-/raw/main/Modulos/s2.sh)
   ;;
   17)
   limit_ssh
   ;;
   18)
   clear
   badvpn
   exit;
   ;;
   19)
   sync & sysctl -w vm.drop_caches=3
   ;;
   20)
   clear
   detalhes
   echo -ne "\n${rojo}ENTER ${amarillo}PARA VOLVER al ${verde}MENU!\e[0m"; read
   ;;
   21)
   menu2
   ;;
   0 | 00)
   echo -e "${rojo}SALIENDO...\e[0m"
   sleep 2
   clear
   exit;
   ;;
   *)
   echo -e "\n${rojo}OPCION INVALIDA !\e[0m"
   sleep 2
esac
done
}
menu
#fim